### ISSUE TITLE
Unable to install on Windows 10 (v0.9.3)

### ISSUE THREAD

**Issue by bwsinger** [joeyballentine/chaiNNer#543]
When trying to install the application either via the executable in "chaiNNer-windows-x64-0.9.3.zip" or running "chaiNNer-0.9.3.Setup.windows.exe" there is an error that comes up.

Running Windows 10 Home (19044.1826)

> The Python backend encountered an unexpected error. ChaiNNer will now exit. Error: Error: spawn C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe ENOENT

<img width="419" alt="python_error" src="https://user-images.githubusercontent.com/16724046/178781977-0d9e2ad7-5ce1-4247-bef3-abee6c5959e0.PNG">

**Comment by joeyballentine** [comment]
The image you uploaded seems to be invalid, could you try uploading it again?

**Comment by bwsinger** [comment]
Updated

**Comment by joeyballentine** [comment]
Can you upload the logs located in appdata/roaming/chaiNNer/logs?

**Comment by bwsinger** [comment]
[main.log](https://github.com/joeyballentine/chaiNNer/files/9104174/main.log)

**Comment by bwsinger** [comment]
Looks like this might have been a conflict when running a VPN at the same time as trying to install the app. With the VPN off, it downloads a local verison of Python, but still errors out. From the logs:

>[2022-07-13 09:26:19.884] [info]  Attempting to check for a port...
[2022-07-13 09:26:19.896] [info]  Port found: 8000
[2022-07-13 09:26:20.161] [info]  Attempting to check Python env...
[2022-07-13 09:26:20.162] [info]  Python not downloaded
[2022-07-13 09:26:20.163] [info]  Downloading standalone python...
[2022-07-13 09:26:21.742] [info]  Done downloading standalone python.
[2022-07-13 09:26:21.742] [info]  Extracting standalone python...
[2022-07-13 09:26:29.928] [info]  Done extracting standalone python.
[2022-07-13 09:26:30.336] [info]  Python version (raw): Python 3.9.7

[2022-07-13 09:26:30.337] [info]  Python version (semver): 3.9.7
[2022-07-13 09:26:30.337] [info]  Final Python binary: C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe
[2022-07-13 09:26:30.337] [info]  {
  python: 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2022-07-13 09:26:30.601] [info]  Attempting to check Python deps...
[2022-07-13 09:26:30.601] [info]  Python executable: C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe
[2022-07-13 09:26:30.602] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2022-07-13 09:26:30.712] [error] Python path configuration:
  PYTHONHOME = 
[2022-07-13 09:26:30.712] [error] 'C:\Python38'
  PYTHONPATH = 'C:\Python38'
  program name = 'C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.base_prefix = 'C:\\Python38'
  sys.base_exec_prefix = 'C:\\Python38'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.prefix = 'C:\\Python38'
  sys.exec_prefix = 'C:\\Python38'
  sys.path = [
    'C:\\Python38',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python39.zip',
    'C:\\Python38\\DLLs',
    'C:\\Python38\\lib',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003808 (most recent call first):
<no Python frame>

[2022-07-13 09:26:30.730] [warn]  Pip process exited with non-zero exit code 1
[2022-07-13 09:26:30.731] [error] Error: Pip process exited with non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\Bradley\AppData\Local\chainner\app-0.9.3\resources\app\.webpack\main\index.js:2:6969)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2022-07-13 09:26:31.646] [info]  Attempting to spawn backend...
[2022-07-13 09:26:31.649] [info]  Successfully spawned backend.
[2022-07-13 09:26:31.686] [error] Backend: Python path configuration:
  PYTHONHOME = 'C:\Python38'
  PYTHONPATH = 'C:\Python38'
  program name = 'C:\Users\Bradley\AppData\Roaming\
[2022-07-13 09:26:31.687] [error] Backend: chaiNNer\python\python\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.base_prefix = 'C:\\Python38'
  sys.base_exec_prefix = 'C:\\Python38'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.prefix = 'C:\\Python38'
  sys.exec_prefix = 'C:\\Python38'
  sys.path = [
    'C:\\Python38',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python39.zip',
    'C:\\Python38\\DLLs',
    'C:\\Python38\\lib',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003dc0 (most recent call first):
<no Python frame>

[2022-07-13 09:26:31.689] [error] Python subprocess exited with code 1 and signal null

**Comment by joeyballentine** [comment]
I'd say try deleting appdata/chaiNNer/python and try running again. I've never seen that error before. If that doesn't work I'll try to do some more research into that error specifically.

**Comment by bwsinger** [comment]
I tried deleting the `C:\Users\Bradley\AppData\Roaming\chaiNNer\python` folder and re-installing. Here are the logs:

```
[2022-07-13 11:02:40.596] [info]  Cleaning up temp folders...
[2022-07-13 11:02:40.598] [info]  Attempting to kill backend...
[2022-07-13 11:02:40.598] [error] Error killing backend.
[2022-07-13 11:03:32.952] [info]  Attempting to check for a port...
[2022-07-13 11:03:32.967] [info]  Port found: 8000
[2022-07-13 11:03:33.218] [info]  Attempting to check Python env...
[2022-07-13 11:03:33.220] [info]  Python not downloaded
[2022-07-13 11:03:33.220] [info]  Downloading standalone python...
[2022-07-13 11:03:35.992] [info]  Done downloading standalone python.
[2022-07-13 11:03:35.993] [info]  Extracting standalone python...
[2022-07-13 11:03:43.910] [info]  Done extracting standalone python.
[2022-07-13 11:03:44.577] [info]  Python version (raw): Python 3.9.7

[2022-07-13 11:03:44.577] [info]  Python version (semver): 3.9.7
[2022-07-13 11:03:44.578] [info]  Final Python binary: C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe
[2022-07-13 11:03:44.578] [info]  {
  python: 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
[2022-07-13 11:03:44.837] [info]  Attempting to check Python deps...
[2022-07-13 11:03:44.838] [info]  Python executable: C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe
[2022-07-13 11:03:44.838] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2022-07-13 11:03:45.050] [error] Python path configuration:
  PYTHONHOME = 'C:\Python38'
  PYTHONPATH = 'C:\Py
[2022-07-13 11:03:45.051] [error] thon38'
  program name = '
[2022-07-13 11:03:45.073] [error] C:\Users
[2022-07-13 11:03:45.073] [error] \Bradley\AppData\Roaming\chaiNNer\python\python\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.base_prefix = 'C:\\Python38'
  sys.base_exec_prefix = 'C:\\Python38'

[2022-07-13 11:03:45.075] [error]   sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'

[2022-07-13 11:03:45.078] [error]   sys.prefix = 'C:\\Python38'
[2022-07-13 11:03:45.079] [error] 
  sys.exec_prefix = 
[2022-07-13 11:03:45.079] [error] 'C:\\Python38'
  sys.path = [
    'C:\\Python38',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python39.zip',
    'C:\\Python38\\DLLs',
    'C:\\Python38\\lib',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002f2c (most recent call first):
<no Python frame>

[2022-07-13 11:03:45.106] [warn]  Pip process exited with non-zero exit code 1
[2022-07-13 11:03:45.107] [error] Error: Pip process exited with non-zero exit code 1
    at ChildProcess.<anonymous> (C:\Users\Bradley\AppData\Local\chainner\app-0.9.3\resources\app\.webpack\main\index.js:2:6969)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2022-07-13 11:03:46.007] [info]  Attempting to spawn backend...
[2022-07-13 11:03:46.011] [info]  Successfully spawned backend.
[2022-07-13 11:03:46.059] [error] Backend: Python path configuration:
  PYTHONHOME = 'C:\Python38'
[2022-07-13 11:03:46.059] [error] Backend: 
  PYTHONPATH = 'C:\Python38'
  program name = 'C:\Users\Bradley\AppData\Roaming\chaiNNer\python\python\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.base_prefix = 'C:\\Python38'
  sys.base_exec_prefix = 'C:\\Python38'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.prefix = 'C:\\Python38'
  sys.exec_prefix = 'C:\\Python38'
  sys.path = [
    'C:\\Python38',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python\\python39.zip',
    'C:\\Python38\\DLLs',
    'C:\\Python38\\lib',
    'C:\\Users\\Bradley\\AppData\\Roaming\\chaiNNer\\python\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004650 (most recent call first):
<no Python frame>

[2022-07-13 11:03:46.063] [error] Python subprocess exited with code 1 and signal null
[2022-07-13 12:11:57.979] [info]  Cleaning up temp folders...
[2022-07-13 12:11:57.981] [info]  Attempting to kill backend...
[2022-07-13 12:11:57.982] [error] Error killing backend.
```

**Comment by joeyballentine** [comment]
Do you have an existing python 3.8 installation? For some reason it seems like that's interfering with this, which is weird because it's supposed to be separate

**Comment by bwsinger** [comment]
The solution for me was to remove the system environment variable "PYTHONHOME". After removing this environment variable and running the Windows installer again, I was able to run the program :)

**Comment by joeyballentine** [comment]
> The solution for me was to remove the system environment variable "PYTHONHOME". After removing this environment variable and running the Windows installer again, I was able to run the program :)

Glad you got it working. I'll look into if there's a way to prevent this from happening in the future
