### ISSUE TITLE
Windows installer loads wrong log file on install error

### ISSUE THREAD

**Issue by jwvanderbeck** [joeyballentine/chaiNNer#746]
Either the installer has somehow been hijacked by spyware or something is very odd.  Went to try this out and the install failed.  When I went to look at the log I was rather shocked at what I found.

Why is this program trying to A) Mess with Discord and B) Install accessibility settings into Windows?!

```
6168> 2022-07-26 11:09:02> Program: Starting Squirrel Updater: --install . -s
6168> 2022-07-26 11:09:02> Program: Starting install, writing to C:\Users\jwvan\AppData\Local\SquirrelTemp
6168> 2022-07-26 11:09:02> Program: About to install to: C:\Users\jwvan\AppData\Local\Discord
6168> 2022-07-26 11:09:02> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
6168> 2022-07-26 11:09:02> CheckForUpdateImpl: Reading RELEASES file from C:\Users\jwvan\AppData\Local\SquirrelTemp
6168> 2022-07-26 11:09:02> CheckForUpdateImpl: Remote version 1.0.9005 differs from local 
6168> 2022-07-26 11:09:02> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
6168> 2022-07-26 11:09:02> ApplyReleasesImpl: Writing files to app directory: C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\chrome_100_percent.pak to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\chrome_100_percent.pak
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\chrome_200_percent.pak to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\chrome_200_percent.pak
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\d3dcompiler_47.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\d3dcompiler_47.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\app.ico to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\app.ico
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\Discord.exe to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\Discord.exe
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\ffmpeg.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\ffmpeg.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\icudtl.dat to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\icudtl.dat
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\installer.db to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\installer.db
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\libEGL.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\libEGL.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\libGLESv2.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\libGLESv2.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\resources.pak to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\resources.pak
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\snapshot_blob.bin to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\snapshot_blob.bin
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\v8_context_snapshot.bin to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\v8_context_snapshot.bin
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\vk_swiftshader.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\vk_swiftshader.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\vulkan-1.dll to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\vulkan-1.dll
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\updater.node to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\updater.node
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Moving file C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\lib\net45\vk_swiftshader_icd.json to C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\vk_swiftshader_icd.json
6168> 2022-07-26 11:09:05> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\Discord.exe]
6168> 2022-07-26 11:09:05> Utility: Process Started: C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\Discord.exe --squirrel-install 1.0.9005, pid 14896
6168> 2022-07-26 11:09:07> Utility: Received exitcode 0 from process C:\Users\jwvan\AppData\Local\Discord\app-1.0.9005\Discord.exe
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: Starting fixPinnedExecutables
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9005
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: File 'C:\Users\jwvan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: File 'C:\Users\jwvan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: Updating shortcut C:\Users\jwvan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: Updating shortcut C:\Users\jwvan\Desktop\Discord.lnk
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: Fixing up tray icons
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9005
6168> 2022-07-26 11:09:07> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9005
```

**Comment by joeyballentine** [comment]
That log file is not from chainner. That looks like a discord log file. Chainner's log file is located in appdata/roaming/chainner/logs

**Comment by jwvanderbeck** [comment]
But it is.  I run the installer from the Release.  It throws an error and then has a button to open the log which gives that.  It is definitely coming from this.

**Comment by jwvanderbeck** [comment]
![Untitled-1](https://user-images.githubusercontent.com/161126/185270137-36f20831-b7e2-4b3c-81ed-928471fdad5c.png)
You can see in the screenshot at the top this is coming from chaiNNer, and clicking that Open Setup Log button gives me what I pasted above.

I KNOW it looks like Discord hence my concern that something isn't right because this app shouldn't be doing anything to Discord

**Comment by joeyballentine** [comment]
If you look at the dates on those logs they're from July 26th. I'm pretty sure it's just opening the wrong log file.

As for why the install is failing, I don't know. And I suppose the chainner logs probably wouldn't even exist if it hasn't been installed properly yet.

I assume the reason it's pulling up a discord log is because discord uses the same electron build tool, or at the very least uses the same .exe packager (called squirrel).

Instead of the installer could you try the zip version?

**Comment by jwvanderbeck** [comment]
Oh great catch on the date in there.  I didn't even notice.  That makes me feel a lot safer and I will try the zip version.

**Comment by jwvanderbeck** [comment]
Portable version works fine!  And now that I realize it wasn't the right log file, my security fears are no more.
