### ISSUE TITLE
[macOS 10.16] Error report for chaiNNer 0.11.0

### ISSUE THREAD

**Issue by jeremyDayslice** [joeyballentine/chaiNNer#748]
Failed to start up on MacOS

Error:
```UnhandledRejection Error: Attempted to register a second handler for 'get-port'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:189:337)
    at /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71868
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EventEmitter.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71371)
```
OS: macOS 10.16

**Comment by joeyballentine** [comment]
Thanks for reporting this. The macos version is not well tested. Was this with the zip version or with the dmg?

**Comment by jeremyDayslice** [comment]
dmg.  I tried disabling the security checks on Mac, thinking maybe it was blocking outbound internet traffic from the app because it wasn't installed from the App Store, but that didn't seem to help.  I also tried to enable my system Python, thinking that might help get around the PyTorch dependencies issue but also no luck.  I will try the zip now though.

**Comment by joeyballentine** [comment]
@jeremyDayslice would you mind uploading that file that it's referencing? I can't personally install the chainner macos distributable and the index.js file it's referencing in this error is different from the one it makes when developing (it's minified) so its impossible for me to see what exactly it's calling that's causing this

**Comment by joeyballentine** [comment]
Specifically I talking about `/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js`

**Comment by joeyballentine** [comment]
@jeremyDayslice, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?

**Comment by jeremyDayslice** [comment]
@joeyballentine it isn't working, it still won't get past the splash screen, but I think it's still trying to use my local Python.  Ever since I enabled the local Python option it hasn't been able to boot up.  Oddly though, there is nothing in my Application Support to delete, so I'm not sure how to restore it to normal functionality.   I'll keep trying though.

**Comment by joeyballentine** [comment]
That's unfortunate. If it pops with a full error message alert box, would you mind sending a screenshot of it?

**Comment by jeremyDayslice** [comment]
Here is the log. It looks like it fails on trying to install `cv2`.   It looks like it is still trying to use my system Python, but it is actually using a Python install that is not the default tied to my PATH, so it is v3.8 instead of v3.9, which might be the problem?

```[2022-08-19 12:58:39.296] [info]  Attempting to check for a port...
[2022-08-19 12:58:39.306] [info]  Port found: 8000
[2022-08-19 12:58:39.558] [info]  Attempting to check Python env...
[2022-08-19 12:58:39.579] [info]  Python version (raw): 
[2022-08-19 12:58:39.616] [info]  Python version (raw): Python 3.8.2

[2022-08-19 12:58:39.617] [info]  Python version (semver): 3.8.2
[2022-08-19 12:58:39.618] [info]  Final Python binary: python3
[2022-08-19 12:58:39.618] [info]  { python: 'python3', version: '3.8.2' }
[2022-08-19 12:58:39.873] [info]  Attempting to check Python deps...
[2022-08-19 12:58:39.874] [info]  Python executable: python3
[2022-08-19 12:58:39.874] [info]  Running pip command: pip list --format=json --disable-pip-version-check
[2022-08-19 12:58:40.408] [info]  Dependency Sanic (sanic) not found.
[2022-08-19 12:58:40.408] [info]  Dependency Sanic Cors (Sanic-Cors) not found.
[2022-08-19 12:58:40.409] [info]  Dependency OpenCV (opencv-python) not found.
[2022-08-19 12:58:40.409] [info]  Dependency NumPy (numpy) not found.
[2022-08-19 12:58:40.409] [info]  Dependency Pillow (PIL) (Pillow) not found.
[2022-08-19 12:58:40.410] [info]  Installing 5 missing dependencies...
[2022-08-19 12:58:40.410] [info]  Python executable: python3
[2022-08-19 12:58:40.410] [info]  Running pip command: pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.5.5.64 numpy==1.22.3 Pillow==9.1.0 --disable-pip-version-check
[2022-08-19 13:01:53.005] [error]   ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-build-env-xlypdrn2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version>='"'"'3.10'"'"''
       cwd: None
  Complete output (85 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/18/1e/7cd4bf0d0c4e109595b5e69621f72c4e01079c533ccb94003dfe361c62ea/setuptools-65.1.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl
  Collecting scikit-build
    Using cached https://files.pythonhosted.org/packages/e3/36/34551e5035757ba17582eb530402a16612ec0446f67f3c7d509f6e9d8e63/scikit_build-0.15.0-py2.py3-none-any.whl
  Collecting cmake
    Using cached https://files.pythonhosted.org/packages/4d/1d/384850073c75a60c67135e7ee85b03a9a6445995061f147d3463286cfbdb/cmake-3.24.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting pip
    Using cached https://files.pythonhosted.org/packages/1f/2c/d9626f045e7b49a6225c6b09257861f24da78f4e5f23af2ddbdf852c99b8/pip-22.2.2-py3-none-any.whl
  Collecting numpy==1.17.3
    Using cached https://files.pythonhosted.org/packages/b6/d6/be8f975f5322336f62371c9abeb936d592c98c047ad63035f1b38ae08efe/numpy-1.17.3.zip
  Collecting distro (from scikit-build)
    Using cached https://files.pythonhosted.org/packages/e1/54/d08d1ad53788515392bec14d2d6e8c410bffdc127780a9a4aa8e6854d502/distro-1.7.0-py3-none-any.whl
  Collecting packaging (from scikit-build)
    Using cached https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl
  Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging->scikit-build)
    Using cached https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl
  Building wheels for collected packages: cmake
    Building wheel for cmake (PEP 517): started
    Building wheel for cmake (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/tmptu97nxah
         cwd: /private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-install-rypl5i_7/cmake
    Complete output (33 lines):
      File "/private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-build-env-n4oxxxqx/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-build-env-n4oxxxqx/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 141, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-build-env-n4oxxxqx/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
        raise SKBuildError(
    Traceback (most recent call last):
  
  
        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cmake:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
           order to retrieve the last manylinux1 compatible wheel.
        3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
           requirements in order to retrieve the last manylinux1 compatible wheel.
        4) Open an issue with the debug information that follows at
           https://github.com/scikit-build/cmake-python-distributions/issues
  
        Python: 3.8.2
        platform: macOS-11.3.1-x86_64-i386-64bit
        macos: 11.3.1
        machine: x86_64
        bits: 64
        pip: 19.2.3
        setuptools: 41.2.0
        scikit-build: 0.15.0
        PEP517_BUILD_BACKEND=setuptools.build_meta
        =============================DEBUG ASSISTANCE=============================
  
    Problem with the CMake installation, aborting build. CMake executable is cmake
    ----------------------------------------
    ERROR: Failed building wheel for cmake
    Running setup.py clean for cmake
  Failed to build cmake
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): still running...
    Building wheel for numpy (setup.py): still running...
    Building wheel for numpy (setup.py): finished with status 'done'
    Created wheel for numpy: filename=numpy-1.17.3-cp38-cp38-macosx_10_14_6_x86_64.whl size=6244162 sha256=7c3e4e63ad4817c7d2e9254183b5750fda5f8454333c3aef4f3fcf6b58fa1a38
    Stored in directory: /Users/jeremy/Library/Caches/pip/wheels/5e/e9/4b/dd5a8eb53e97dfcc1314eca9c6769edd3cad379d6644c1ad94
  Successfully built numpy
  ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly
  WARNING: You are using pip version 19.2.3, however version 22.2.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------

[2022-08-19 13:01:53.764] [error] ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/g5/l42b3qfx0y32rcr5zsfz2vc40000gn/T/pip-build-env-xlypdrn2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version>='"'"'3.10'"'"'' Check the logs for full command output.

[2022-08-19 13:01:53.833] [warn]  Pip process exited with non-zero exit code 1
[2022-08-19 13:01:53.834] [error] Error: Pip process exited with non-zero exit code 1
    at ChildProcess.<anonymous> (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:7146)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[2022-08-19 13:01:54.100] [info]  Attempting to spawn backend...
[2022-08-19 13:01:54.102] [info]  Successfully spawned backend.
[2022-08-19 13:01:54.225] [error] Backend: Traceback (most recent call last):
  File "/Applications/chaiNNer.app/Contents/Resources/src/run.py", line 14, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

[2022-08-19 13:01:54.231] [error] Python subprocess exited with code 1 and signal null
[2022-08-19 13:04:40.208] [info]  Cleaning up temp folders...

```

If I could find where the `localStorage` is actually getting stored I could at least stop it from using my Python.

**Comment by jeremyDayslice** [comment]
To be specific, It is using `/Library/Developer/CommandLineTools/usr/bin/python3` (3.8) instead of `/usr/local/bin/python3` (3.9)

**Comment by joeyballentine** [comment]
Interesting. Which version shows up when you type `python3 --version` in the terminal?

**Comment by jeremyDayslice** [comment]
```
> /Library/Developer/CommandLineTools/usr/bin/python3 --version
Python 3.8.2

> which python3
/usr/local/bin/python3

> python3 --version
Python 3.9.6
```

**Comment by joeyballentine** [comment]
In that case I'm going to assume what I did to remove the PYTHONHOME environment variable from the python commands is what's causing that. This was to fix a different issue where it was causing some users who were trying to use integrated python to accidentally use their system python. So kinda the opposite of what's going on here. 

Are you in the Discord server? I could send you a test build to try out to see if that really is the issue

**Comment by jeremyDayslice** [comment]
I am, @ferdawins.  Thanks.

**Comment by joeyballentine** [comment]
@jeremyDayslice you ended up getting this fixed, right?

**Comment by joeyballentine** [comment]
Confirmed it is working for him.
