### ISSUE TITLE
Error report for chaiNNer 0.11.2

### ISSUE THREAD

**Issue by jind11** [joeyballentine/chaiNNer#797]
Error:
```UnhandledRejection Error: Attempted to register a second handler for 'get-port'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:189:337)
    at /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:72010
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71513
```
OS: macOS 10.17

**Comment by joeyballentine** [comment]
Hi. We believe we have resolved this and the fix should be released later tonight.

**Comment by jind11** [comment]
Thank you for the quick reply. Finger crossed!

**Comment by joeyballentine** [comment]
@jind11, please test the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.3) and let me know if this issue is fixed.
