### ISSUE TITLE
Can't `setup` or `run` it

### ISSUE THREAD

**Issue by scillidan** [joeyballentine/chaiNNer#924]
- Chainner version: Alpha v0.12.3
- OS: Windows 10

I tried run it from the `..setup.exe` and `.zip`, and don't work both.
It warning:
![image](https://user-images.githubusercontent.com/19889610/189482003-1c1126f3-67bd-4f89-a84b-c6d86ccd9b9c.png)

Here are logs in `cmd`:
```
D:\ketarin\chainner λ 19:42:18.924 > Attempting to check for a port...
19:42:18.939 > Port found: 8000
19:42:19.191 > Attempting to check Python env...
19:42:19.193 > Python not downloaded
19:42:19.194 > Downloading standalone python...
19:42:19.219 > Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)   
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at ssl.onhandshakedone (node:_tls_wrap:727:12)
19:42:19.250 > Final Python binary: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
19:42:19.250 > {
  python: 'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: 'unknown'
}
19:42:19.513 > Attempting to check Python deps...
19:42:19.514 > Python executable: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
19:42:19.514 > Running pip command: pip list --format=json --disable-pip-version-check
19:42:19.516 > Pip process errored: Error: spawn C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe ENOENT
19:42:19.516 > Error: spawn C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
19:42:19.952 > Attempting to spawn backend...
19:42:19.954 > Successfully spawned backend.
19:42:19.955 > Python subprocess encountered an unexpected error: Error: spawn C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe ENOENT
```

**Comment by joeyballentine** [comment]
Looks like it was unable to download the integrated python. Do you have strict firewall settings?

**Comment by scillidan** [comment]
I used the default level of firewall Settings, and seems I didn't see a new notice about network connection. So It should be no was blocked by the firewall, I guess🤔.
Usually, when I was using the python to install package, will shut down the `network proxy`. After then, it is functioning normally.

I have just read the log carefully.
Then the file, `C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe` not be found there. 
![image](https://user-images.githubusercontent.com/19889610/189512926-a759747c-ff70-4116-8342-30da577e50dc.png)
And I used the [scoop](https://scoop.sh/) to install python. There is the [.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/python.json) of python. 
The `python.exe` is on here, `C:\Users\scillidan\scoop\apps\python\current\python.exe`.

**Comment by joeyballentine** [comment]
At some point I'll be allowing the switch to system python if the integrated download fails. The startup process was designed assuming the download would always work.

For now you should be able to copy a working python 3.9 into chaiNNer's python folder so that `C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe` exists

**Comment by scillidan** [comment]
I install the `python 3.9.13`, and copy the `python.exe` to `C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python`.
It can launch now... but down then.

```cmd
D:\ketarin\chainner λ chainner.exe 

D:\ketarin\chainner λ 16:12:24.077 > Attempting to check for a port...
16:12:24.091 > Port found: 8000
16:12:24.343 > Attempting to check Python env...
16:12:24.385 > Final Python binary: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
16:12:24.386 > {
  python: 'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',  
  version: 'unknown'
}
16:12:24.653 > Attempting to check Python deps...
16:12:24.653 > Python executable: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
16:12:24.654 > Running pip command: pip list --format=json --disable-pip-version-check     
16:12:24.680 > Pip process exited with non-zero exit code 3221225781
16:12:24.681 > Error: Pip process exited with non-zero exit code 3221225781
    at ChildProcess.<anonymous> (D:\ketarin\chainner\resources\app\.webpack\main\index.js:2:7129)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
16:12:25.071 > Attempting to spawn backend...
16:12:25.075 > Successfully spawned backend.
16:12:25.094 > Python subprocess exited with code 3221225781 and signal null
16:13:57.316 > Attempting to kill backend...
16:13:57.317 > Error killing backend.
16:13:57.317 > Cleaning up temp folders...
on\python\python.exe
16:08:08.684 > Running pip command: pip list --format=json --disable-pip-version-check     
16:08:08.711 > Pip process exited with non-zero exit code 3221225781
16:08:08.712 > Error: Pip process exited with non-zero exit code 3221225781
    at ChildProcess.<anonymous> (D:\ketarin\chainner\resources\app\.webpack\main\index.js:2:7129)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
16:08:09.104 > Attempting to spawn backend...
16:08:09.111 > Successfully spawned backend.
16:08:09.132 > Python subprocess exited with code 3221225781 and signal null
```
![image](https://user-images.githubusercontent.com/19889610/189600889-34c06f38-67bd-4f38-a71a-73cb203c5e42.png)

**Comment by joeyballentine** [comment]
Is this still happening for you?

**Comment by scillidan** [comment]
Yes, man. Still error:
```
20:12:16.032 > Port found: 8000
20:12:16.296 > Attempting to check Python env...
20:12:16.329 > Final Python binary: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
20:12:16.330 > {
  python: 'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe',
  version: '3.9.7'
}
20:12:16.592 > Attempting to check Python deps...
20:12:16.593 > Python executable: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
20:12:16.594 > Running pip command: pip list --format=json --disable-pip-version-check
20:12:16.873 > Installing/Updating dependencies...
20:12:16.874 > Python executable: C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\python.exe
20:12:16.874 > Running pip command: pip install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.6.0.66 numpy==1.23.2 Pillow==9.2.0 pywin32==304 --disable-pip-version-check       
[14636:0916/201415.944:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
21:05:34.394 > ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\http\client.py", line 462, in read
    n = self.readinto(b)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\http\client.py", line 506, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
    super().__init__(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
    for chunk in chunks:
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
    for x in it:
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\scillidan\AppData\Roaming\chaiNNer\python\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

21:05:34.524 > Pip process exited with non-zero exit code 2
21:05:34.525 > Error: Pip process exited with non-zero exit code 2
    at ChildProcess.<anonymous> (D:\home\chaiNNer-windows-x64-0.12.6\resources\app\.webpack\main\index.js:2:7455)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
21:05:34.788 > Attempting to spawn backend...
21:05:34.796 > Successfully spawned backend.
21:05:34.926 > Backend: Traceback (most recent call last):
  File "D:\home\chaiNNer-windows-x64-0.12.6\resources\src\run.py", line 14, in <module>

21:05:34.928 > Backend:     import cv2
ModuleNotFoundError: No module named 'cv2'

21:05:34.945 > Python subprocess exited with code 1 and signal null
21:38:55.846 > Attempting to kill backend...
21:38:55.854 > Error killing backend.
21:38:55.855 > Cleaning up temp folders...
```

But can‘t install `cv2`:
```
chaiNNer\python\python λ .\python.exe -m pip install opencv-python
Python path configuration:
  PYTHONHOME = 'C:\Users\scillidan\scoop\apps\python\currentC:\Users\scillidan\scoop\apps\python\current'
  PYTHONPATH = 'C:\Users\scillidan\scoop\apps\python\current\python.exeC:\Users\scillidan\scoop\apps\python\current\python.exe'
  program name = '.\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.base_prefix = 'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current'     
  sys.base_exec_prefix = 'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python.exe'
  sys.prefix = 'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current'
  sys.exec_prefix = 'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current'     
  sys.path = [
    'C:\\Users\\scillidan\\scoop\\apps\\python\\current\\python.exeC:\\Users\\scillidan\\scoop\\apps\\python\\current\\python.exe',
    'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python\\python39.zip',
    'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current\\DLLs',
    'C:\\Users\\scillidan\\scoop\\apps\\python\\currentC:\\Users\\scillidan\\scoop\\apps\\python\\current\\lib',
    'C:\\Users\\scillidan\\AppData\\Roaming\\chaiNNer\\python\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002e34 (most recent call first):
<no Python frame>
```
I need to use the proxy to install some package.Before then, I download `numpy-1.23.3-cp310-cp310-win_amd64.whl` and `opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl` etc, use `python install .whl` to install these. 
I install the 
If I can manually to install the dependence step by step, may be able to solved it.
Thanks your time.

**Comment by joeyballentine** [comment]
did you block chaiNNer from having Internet access? 

If you really want to install stuff manually to your system python, then you'll also have to manually change the setting file that controls that option, since you can't change that until you open into chaiNNer properly

**Comment by scillidan** [comment]
My fault, I forget to delete `env` set. I delete the `PYTHONPATH` and `PYTHONHOME`.
It can run now.
![image](https://user-images.githubusercontent.com/19889610/190658899-7a67b681-d80e-46b3-bbbc-5cdbab1070ce.png)
Beautiful UI :)

**Comment by joeyballentine** [comment]
Awesome, glad you got it working
